### ISSUE TITLE
vue에는 package.json이 없나요?

### ISSUE THREAD

**Issue by ingyeoking13** [gumgu/bien-portfolio#1]
vue 에는 package.json이 없나요 어떻게 빌드하는지 ...!

**Comment by gumgu** [comment]
헉 제가 깃허브 사용에 아직 미숙해서 그 부분도 업로드해야 하는 줄 몰랐네요... 찾아보고 추가하겠습니다, 말씀해주셔서 너무 감사합니다!!

**Comment by ingyeoking13** [comment]
https://github.com/gumgu/bien-portfolio/commit/a09960597a8276801b3971b18aa109987bd2b653
